steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--target', 'dependencies', '--cache-from', ',gcr.io/$PROJECT_ID/reminders-deps', '-t' ',gcr.io/$PROJECT_ID/reminders-deps', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--target', 'app', '--cache-from', 'gcr.io/$PROJECT_ID/reminders-deps:latest', '-t', 'gcr.io/$PROJECT_ID/reminders', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', '--image', 'gcr.io/$PROJECT_ID/reminders', '--name', 'reminders', '--region', 'europe-west1', '--platform', 'managed']
